package com.feiniu.pmadmin.dao;

import com.feiniu.pmadmin.entity.TxdPromItemsEntity;
import org.apache.ibatis.annotations.Param;

public interface TxdPromItemsEntityMapper {
    int deleteByPrimaryKey(Integer id);

    int insert(TxdPromItemsEntity record);

    int insertSelective(TxdPromItemsEntity record);

    TxdPromItemsEntity selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(TxdPromItemsEntity record);

    int updateByPrimaryKey(TxdPromItemsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txd_prom_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") java.util.List<TxdPromItemsEntity> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txd_prom_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") java.util.List<TxdPromItemsEntity> list, @Param("selective") TxdPromItemsEntity.Column ... selective);
}