package com.feiniu.pmadmin.dao;

import com.feiniu.pmadmin.entity.TxdPromotionsEntity;
import org.apache.ibatis.annotations.Param;

public interface TxdPromotionsEntityMapper {
    int deleteByPrimaryKey(Integer id);

    int insert(TxdPromotionsEntity record);

    int insertSelective(TxdPromotionsEntity record);

    TxdPromotionsEntity selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(TxdPromotionsEntity record);

    int updateByPrimaryKey(TxdPromotionsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txd_promotions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") java.util.List<TxdPromotionsEntity> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txd_promotions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") java.util.List<TxdPromotionsEntity> list, @Param("selective") TxdPromotionsEntity.Column ... selective);
}