package com.feiniu.pmadmin.entity;

import java.util.Date;

public class TxdPromotionsEntity {
    private Integer id;

    private String promotionNo;

    private String storeId;

    private Date startTime;

    private Date endTime;

    private Date buyBeginTime;

    private Date buyEndTime;

    private String memo;

    private Integer spStoreNo;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPromotionNo() {
        return promotionNo;
    }

    public void setPromotionNo(String promotionNo) {
        this.promotionNo = promotionNo;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getBuyBeginTime() {
        return buyBeginTime;
    }

    public void setBuyBeginTime(Date buyBeginTime) {
        this.buyBeginTime = buyBeginTime;
    }

    public Date getBuyEndTime() {
        return buyEndTime;
    }

    public void setBuyEndTime(Date buyEndTime) {
        this.buyEndTime = buyEndTime;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getSpStoreNo() {
        return spStoreNo;
    }

    public void setSpStoreNo(Integer spStoreNo) {
        this.spStoreNo = spStoreNo;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table txd_promotions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        promotionNo("promotion_no"),
        storeId("store_id"),
        startTime("start_time"),
        endTime("end_time"),
        buyBeginTime("buy_begin_time"),
        buyEndTime("buy_end_time"),
        memo("MEMO"),
        spStoreNo("sp_store_no");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table txd_promotions
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table txd_promotions
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table txd_promotions
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table txd_promotions
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table txd_promotions
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table txd_promotions
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}